### ISSUE TITLE
Create separate WS topic for every event

### ISSUE THREAD

**Issue by andkantor** [microservicesteam/project-adele#48]
Topic can be sector specific as well, so the user receives only the necessary TicketEvents. No useless TicketEvents received.

**Comment by andkantor** [comment]
@bearcheese shall we close this after you implemented it for sector?

**Comment by kelemena** [comment]
@andkantor PR is not merged yet ;)

**Comment by andkantor** [comment]
@kelemena true :)

**Comment by bearcheese** [comment]
Fixed by #49
