### ISSUE TITLE
Align model in TicketMaster and Booking module

### ISSUE THREAD

**Issue by andkantor** [microservicesteam/project-adele#59]
It is a bit misleading that in Booking module the Position is an integer, but in the TicketMaster it's not, and actually it contains the eventId. Because of this Position object seems more likely a Ticket object (which would have the eventId/sectorId/position(seat))

Booking module
- Add sectorId to Ticket object

TicketMaster module
- Add all fields from Position to Ticket object
- Generate some ticketId on Ticket construction which can be used in the HashMap (e.g.: a derived field)

**Comment by bearcheese** [comment]
Fixed with #62
